version: "3"

services:
  jupyter:
    build: .
    container_name: jupyter-lab
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/workspace/config/key.json"
    command: >
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --allow-root
      --no-browser
      --ServerApp.token="mysecuretoken"
